"""match cities on a folded key

Revision ID: 02c07e363cd8
Revises: 48a1451ccd07
Create Date: 2026-09-23 20:11:27.781306

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02c07e363cd8'
down_revision: Union[str, Sequence[str], None] = '48a1451ccd07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("weather_readings", sa.Column("city_key", sa.String(length=120), nullable=True))

    # Backfill with the same folding the application uses, so existing rows stay
    # findable. Done in Python rather than SQL because Postgres has no built-in
    # accent folding without the unaccent extension.
    from sqlalchemy import table, column, String, select, update as sa_update
    from app.domain.city_key import city_key

    readings = table("weather_readings", column("id"), column("city", String), column("city_key", String))
    bind = op.get_bind()
    for row_id, name in bind.execute(select(readings.c.id, readings.c.city)).fetchall():
        bind.execute(sa_update(readings).where(readings.c.id == row_id).values(city_key=city_key(name)))

    op.alter_column("weather_readings", "city_key", nullable=False)
    op.drop_index(op.f('ix_weather_readings_city_lower'), table_name='weather_readings')
    op.drop_index(op.f('ix_weather_readings_city_recency'), table_name='weather_readings')
    op.create_index('ix_weather_readings_city_recency', 'weather_readings', ['city_key', sa.literal_column('observed_at DESC'), sa.literal_column('fetched_at DESC')], unique=False)
    op.create_index('ix_weather_readings_city_key', 'weather_readings', ['city_key'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_weather_readings_city_key', table_name='weather_readings')
    op.drop_index('ix_weather_readings_city_recency', table_name='weather_readings')
    op.create_index(op.f('ix_weather_readings_city_recency'), 'weather_readings', ['city', sa.literal_column('observed_at DESC'), sa.literal_column('fetched_at DESC')], unique=False)
    op.create_index(op.f('ix_weather_readings_city_lower'), 'weather_readings', [sa.literal_column('lower(city::text)')], unique=False)
    op.drop_column('weather_readings', 'city_key')
    # ### end Alembic commands ###
