"""store weather description

Revision ID: 48a1451ccd07
Revises: ee455bf74672
Create Date: 2026-09-23 19:43:02.457517

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48a1451ccd07'
down_revision: Union[str, Sequence[str], None] = 'ee455bf74672'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Add the stored WMO description.

    Added nullable and backfilled before being made NOT NULL: adding a NOT NULL
    column with no default fails outright on a table that already has rows.
    Existing rows are backfilled from their weathercode using the same WMO
    table the application uses.
    """
    op.add_column("weather_readings", sa.Column("description", sa.String(length=120), nullable=True))

    from app.domain.weather_codes import WMO_DESCRIPTIONS

    cases = " ".join(
        f"WHEN {code} THEN '{text.replace(chr(39), chr(39) * 2)}'"
        for code, text in WMO_DESCRIPTIONS.items()
    )
    op.execute(
        f"UPDATE weather_readings SET description = CASE weathercode {cases} "
        "ELSE 'Unknown weather code ' || weathercode END"
    )

    op.alter_column("weather_readings", "description", nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("weather_readings", "description")
    # ### end Alembic commands ###
