"""replace items with weather_readings

Revision ID: ee455bf74672
Revises: 6e955afa4f46
Create Date: 2026-09-22 20:39:45.191535

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ee455bf74672'
down_revision: Union[str, Sequence[str], None] = '6e955afa4f46'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weather_readings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('city', sa.String(length=120), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('temperature_c', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('windspeed_kmh', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('winddirection_deg', sa.Integer(), nullable=False),
    sa.Column('weathercode', sa.Integer(), nullable=False),
    sa.Column('is_day', sa.Boolean(), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_weather_readings_city_lower', 'weather_readings', [sa.literal_column('lower(city)')], unique=False)
    op.create_index('ix_weather_readings_city_recency', 'weather_readings', ['city', sa.literal_column('observed_at DESC'), sa.literal_column('fetched_at DESC')], unique=False)
    op.drop_index(op.f('ix_items_name'), table_name='items')
    op.drop_table('items')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('items',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('items_pkey'))
    )
    op.create_index(op.f('ix_items_name'), 'items', ['name'], unique=False)
    op.drop_index('ix_weather_readings_city_recency', table_name='weather_readings')
    op.drop_index('ix_weather_readings_city_lower', table_name='weather_readings')
    op.drop_table('weather_readings')
    # ### end Alembic commands ###
